### ISSUE TITLE
404-ing links in README

### ISSUE THREAD

**Issue by paulilli** [jquery/jquery-release#71]
Seems like you've got some broken links in the readme:

> You need local clones of fake-project and fake-cdn, then update both variables to point to those.

I can't seem to find the `fake-project` and `fake-cdn` projects (github is giving me a 404). Are those repos moved or do I need to use another repo?

**Comment by scottgonzalez** [comment]
They're both private because we don't want junk repos polluting our public account.

**Comment by paulilli** [comment]
@scottgonzalez Understandable but this prevents any contributions from non-members of the team.

**Comment by scottgonzalez** [comment]
Do you have a suggestion for an API change? Even if it weren't private, you still wouldn't be able to push to it. You'd need to configure the repos to use.

**Comment by paulilli** [comment]
> Even if it weren't private, you still wouldn't be able to push to it. You'd need to configure the repos to use.

Forking it and use those repos to test? (which you then have push access to)

**Comment by paulilli** [comment]
I might be misunderstanding you, I just know it prevents me (and others?) to contribute. Currently the maximum amount of contributors you will have for this repo are the 44 people which the repo is visible to.

**Comment by scottgonzalez** [comment]
I'll ask again: Do you have a suggestion for an API change?

Do you want command line options for the repos? That's the only per-user configuration that exists.

**Comment by scottgonzalez** [comment]
> I might be misunderstanding you, I just know it prevents me (and others?) to contribute. Currently the maximum amount of contributors you will have for this repo are the 44 people which the repo is visible to.

I'm not sure where you got 44 from, the number of people with access to the fake repos is actually much smaller (it's the people who actually manage releases).

Anyway, you can easily work on the release script right now by locally changing the two lines that reference the fake repos.

**Comment by paulilli** [comment]
> I'll ask again: Do you have a suggestion for an API change?

Make the repos public, like a good __open__ source citizen should do.

> Do you want command line options for the repos?

optionally, yes, why not.

> I'm not sure where you got 44 from, the number of people with access to the fake repos is actually much smaller

Haha, makes it even worse :trollface: Can't everybody in an org see the private repos of that org?

> Anyway, you can easily work on the release script right now by locally changing the two lines that reference the fake repos.

Thanks for the advice, it was the only thing I needed to know, but still, not ideal.

**Comment by arschmitz** [comment]
@paulilli I'm no sure I see the value in making these links usable, they are literally empty repos what value do they provide, besides confusion for people that see them and clutter?

**Comment by scottgonzalez** [comment]
fake-project isn't empty. It minimally integrates with the release script to actually test functionality and has specific tags for safe restoring.

**Comment by paulilli** [comment]
> I'm no sure I see the value in making these links usable, they are literally empty repos what value do they provide, besides confusion for people that see them and clutter?

Don't 404-ing links confuse even more people?

> fake-project isn't empty. It minimally integrates with the release script to actually test functionality and has specific tags for safe restoring.

That's exactly what I mean, you can't just go test the script without those repos.

**Comment by scottgonzalez** [comment]
@paulilli Can you please explain what you're trying to do? Are you trying to work on jquery-release directly or are you trying to use it on a project? The latter would never use fake-project.

**Comment by paulilli** [comment]
> @paulilli Can you please explain what you're trying to do? Are you trying to work on jquery-release directly or are you trying to use it on a project? The latter would never use fake-project.

I wanted to submit a PR for https://github.com/jquery/jquery-release/issues/72, and as your own contribution guidelines say, I should be able to test things manually.

**Comment by paulilli** [comment]
Also, in some way I feel like private repos don't fit within the Foundation's vision. *open*-source right? Are there any other hidden projects you're keeping hidden?

**Comment by timmywil** [comment]
> Are there any other hidden projects you're keeping hidden?

Our infrastructure repo for jQuery servers is also private. Developers don't share their ssh keys either. It doesn't make them bad open source citizens.

**Comment by ajpiano** [comment]
I don't think it would be harmful for us to open these repos up, even though they're "junk repos". If people see a project on the jQuery github called "fake-project" and it makes them wonder what that's all about, that seems like a perfectly fine outcome.

**Comment by paulilli** [comment]
If those repos have a clear readme nobody is going to be confused.

> Our infrastructure repo for jQuery servers is also private. 

Well, I actually think that's sad too. There are many smart guys around, and you're __not letting__ them contribute. How can people contribute to something they don't know exists?

**Comment by paulilli** [comment]
Hope you don't take me wrong saying it like that. I love the work you're doing!
