### ISSUE TITLE
Please use `chalk` instead of `colors.js`

### ISSUE THREAD

**Issue by paulilli** [jquery/jquery-release#72]
Seems like currently this repo uses the `colors` module to get colors in the terminal. You'd better consider using an alternative, @sindresorhus [chalk](https://github.com/sindresorhus/chalk#why) for example. `colors.js` has many disadvantages (see chalk's readme).

**Comment by jzaefferer** [comment]
Sounds good to me, I've made the switch in other projects as well. Are you interested in making that change and send a PR?

**Comment by jbnicolai** [comment]
@jzaefferer I'd be happy to look into it.

**Comment by jbnicolai** [comment]
@jzaefferer @paulilli done. Hope I caught them all (the implicit changing of the string prototype means having to hunt down all references to `/\.red/`, etc)

**Comment by scottgonzalez** [comment]
Presumably you could just search for `".`

**Comment by scottgonzalez** [comment]
Oh, but we run this on a lot of variables too. :-/

**Comment by jbnicolai** [comment]
> Oh, but we run this on a lot of variables too. :-/

Exactly. And it seems it only worked in most files because `colors` happened to be a transitive dependency, as only one file actually `require`'d it in

**Comment by scottgonzalez** [comment]
> And it seems it only worked in most files because colors happened to be a transitive dependency, as only one file actually require'd it in

Or more accurately, we only required it in one module because that's how it's designed to work.
