### ISSUE TITLE
npm-tag is deprecated

### ISSUE THREAD

**Issue by jzaefferer** [jquery/jquery-release#79]
From a recent release:

```
npm tag qunitjs@1.18.0 beta
npm WARN tag This command is deprecated. Use `npm dist-tag` instead.
```

Haven't yet looked into the details.

**Comment by mzgol** [comment]
Yup, but `dist-tag` has been added somewhere around npm `2.5`. So if we want to use it we'd have to add a guard at the beginning of the release process to ensure we have recent npm. Note that all Node 0.10 versions include some flavor of `npm@1`, only Node >=0.12.2 or recent io.js versions include acceptable npm versions by default.

Note that IMO making sure we're on a recent npm would be a good idea anyway. `npm@1` has some race conditions that have been long fixed so depending on it in the middle of the release process is asking for problems.

**Comment by mgol** [comment]
Done in #92.
