### ISSUE TITLE
current version not properly calculated on windows

### ISSUE THREAD

**Issue by staabm** [jquery/jquery-release#89]
on windows7 I am getting the following output

```
##
## CALCULATING VERSIONS
##

Validating current version...
We are going from '1.14.0' to 1.15.0.
After the release, the version will be 1.15.1-pre.
```

because of the single quotes arround the "current detected version" the whole release process fails

running my fork https://github.com/staabm/jquery-release  against https://github.com/jzaefferer/jquery-validation

**Comment by dmethvin** [comment]
How did you get the quotes there? What does your command line look like?

**Comment by staabm** [comment]
I didnt put the quotes there. the version number were auto calculated by the release script

**Comment by staabm** [comment]
this seem to fix it on windows https://github.com/jquery/jquery-release/pull/90
